### ISSUE TITLE
No ETotal

### ISSUE THREAD

**Issue by dmurphydrtc** [porjo/gosuntwins#3]
Firstly thanks for writing and sharing the software.

I have hooked my JFY 3300TL to a Raspberry Pi and managed to install and run your software.

Here is a sample o/p;

2016/04/03 16:54:24 Initializing inverter: => A5A50100304400FE410A0D
2016/04/03 16:54:25 Identifying inverter: =>  A5A50100304000FE450A0D
2016/04/03 16:54:25 Read data: <=  A5A5000030BF1031353230313332303130303937202020FAC80A0D
2016/04/03 16:54:26 Register inverter: =>  A5A501003041113135323031333230313030393720202001FB430A0D
2016/04/03 16:54:26 Read data: <=  A5A5010130BE0106FDBF0A0D
2016/04/03 16:54:26 Requesting current readings: => A5A50101314200FE410A0D
2016/04/03 16:54:26 Read data: <=  A5A5010131BD30014506F6017200020000023800030996138800E0FFFF0000A89900000000000100000000000000000000000000
000000F6480A0D
2016-04-03 16:54:26.526247456 +1000 AEST, 32.500, 37.000, 0.200, 5.680, 0.300, 245.400, 50.000, 22.400

My system generated 5.68kw today (other readings like hertz 50hz & voltage 245vac seem fine) however I don't see my Etotal figure (as read from JFY inverter) of 4445KwH in the output...

Is there something I am missing or modify in the code to display this parameter?

(PS - I am an enthusiast ...not a programmer ). Any help would be much appreciated.

**Comment by porjo** [comment]
I'm glad you find it useful.

I don't believe Etotal was available when I tested last (it's been a couple of years!). There are a couple of 'unknown' fields in the raw data which may correspond with Etotal, although that could be model or firmware dependent also.

If you upload to pvoutput.org, it will keep a running total for you.

**Comment by dmurphydrtc** [comment]
Ian,

Thanks for getting back to me. Thought I'd ask the question. Will get it up
and running on pvoutput.org as you suggested.

Ta again.
